#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ScholarStation.Resource", IsApplication=true)]

namespace ScholarStation
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ximd90I = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int CreateStudySession = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int CreateTutorSession = 2131099648;
			
			// aapt resource value: 0x7f06000b
			public const int LoginButton = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int Password = 2131099658;
			
			// aapt resource value: 0x7f060006
			public const int ProfileButton = 2131099654;
			
			// aapt resource value: 0x7f06000d
			public const int SignIn = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int SignUp = 2131099662;
			
			// aapt resource value: 0x7f060014
			public const int StudentAge = 2131099668;
			
			// aapt resource value: 0x7f060011
			public const int StudentEmail = 2131099665;
			
			// aapt resource value: 0x7f06000f
			public const int StudentFName = 2131099663;
			
			// aapt resource value: 0x7f060015
			public const int StudentGender = 2131099669;
			
			// aapt resource value: 0x7f060010
			public const int StudentLName = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int StudentMajor = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int StudentYear = 2131099667;
			
			// aapt resource value: 0x7f06001c
			public const int TutorAge = 2131099676;
			
			// aapt resource value: 0x7f060019
			public const int TutorEmail = 2131099673;
			
			// aapt resource value: 0x7f060017
			public const int TutorFName = 2131099671;
			
			// aapt resource value: 0x7f06001d
			public const int TutorGender = 2131099677;
			
			// aapt resource value: 0x7f060018
			public const int TutorLName = 2131099672;
			
			// aapt resource value: 0x7f06001a
			public const int TutorMajor = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int TutorYear = 2131099675;
			
			// aapt resource value: 0x7f060008
			public const int UserName = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int Welcome = 2131099660;
			
			// aapt resource value: 0x7f060016
			public const int imageView1 = 2131099670;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout1 = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout2 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout3 = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int linearLayout4 = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int textView1 = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int textView2 = 2131099657;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int HomeScreen = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Login = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int StartScreen = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int StudentProfile = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int TutorProfile = 2130968580;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
